### ISSUE TITLE
Implement queue purge

### ISSUE THREAD

**Issue by Asitha** [ballerina-platform/ballerina-message-broker#142]
**Description:**

Implement queue purging functionality for queues. This should accompany the corresponding REST Admin API functionality as well.

**Comment by a5anka** [comment]
According to the spec, this method removes all messages from a queue which are not awaiting acknowledgment.

Additional guidelines for implementers:
- The server MUST NOT purge messages that have already been sent to a client but not yet acknowledged.
- The server MAY implement a purge queue or log that allows system administrators to recover accidentally­purged messages. The server SHOULD NOT keep purged messages in the same storage spaces as the live messages since the volumes of purged messages may get very large.

In the initial version, we will purge the queue when there are no consumers. 

WDYT?
